name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    format:
        name: Format
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 7.0.x
            - name: Check formatting
              run: dotnet format --verify-no-changes
    build:
        name: Build
        runs-on: ubuntu-latest
        needs: format
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 7.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --no-restore